### ISSUE TITLE
Battery charging on and off and conflict when dual booting with windows.

### ISSUE THREAD

**Issue by b1t0y** [balopez83/Surface_Pro_3_Hackintosh#31] opened 2024-05-30 14:48 UTC
@balopez83 

I have an Surface pro 3 with I7 and 256gb.  I am dual booting with Windows.   I was able to successfully install Sonoma with opencore efi with your latest release.   However,  I noticed that when my charger is plugged on OSX the battery toggles to charging sign to adapter sign several times.  Mostly it often happens when opening apps or watching videos.  It still chargers but its kinda slow because of it.  I tried 2 different chargers and issue still persisted.

Now,  when I boot Windows through opencore.  My battery icon in windows always says fully charge and charging sign always on even charger is not plugged in and stays at 100% charged even its been used for hours. But it works normal if I use different booloader such as refind or directly with windows boot manager.  I'm using booticex64 in windows to use different bootloader.  I think there might be a conflict with an SSDT, kext or something in opencore that makes that windows battery not work well.  Did you ever experience this with dual booting? 

Any ideas on what to do or how can I resolve the conflict?  Thanks for this project.  It has been a treat to be able to have a tablet MacOS.  

Btw, I think this is the same issue that was closed.

https://github.com/balopez83/Surface_Pro_3_Hackintosh/issues/12

Thank you again.

**Comment by balopez83** [comment] 2024-05-31 05:23
@b1t0y did you change the version of OpenCore on your EFI? The issue you are describing was resolved by switching to the OpenCore mod fork which allows you to turn os SSDT loading in Windows which is not supported in the main OpenCore branch. 

The issue is due to poor ACPI code common in this generation of computers. Unfortunately the computer does not respect renames and supplemental code redirects as it should and despite having tried all the proper methods of only having the battery code running in macOS only, the system still loads it in Windows. The OpenCore Mod fork allows for SSDTs to not be loaded in any OS other than macOS. 

If you swapped or upgraded OpenCore I highly recommend reverting to the last release in this repo as upgrading OpenCore won't provide any benefit at this time.

The charging indicator you mentioned should be related to the issue you linked. It is cosmetic only and does not impact charging. Charging is slower at times running macOS though I suspect there is some power management that occurs with Windows that isn't available in macOS. Also if your system is indexing it can draw extra power which slows charging though that usually temporary. 

Hope this helps a bit

**Comment by balopez83** [comment] 2024-08-05 23:37
Closing due to no activity. Please open if you are still experiencing this issue.

**Closed as completed by balopez83** 2024-08-05 23:37 UTC
