### ISSUE TITLE
Secure boot not working

### ISSUE THREAD

**Issue by theholyjosh1** [balopez83/Surface_Pro_3_Hackintosh#16] opened 2023-07-04 09:51 UTC
I done everything on the tutorial on the GitHub page on how to turn on secure boot. But when i boot now, a menu shows and I don’t see an option to boot macOS.![image](https://github.com/balopez83/Surface_Pro_3_Hackintosh/assets/118050388/63726725-dd11-4397-9454-d78a31a11b89)

**Comment by balopez83** [comment] 2023-07-04 16:17
@ShibeGG1 do you have more OS's installed other than macOS? Also did you try to download a new version of the certificate or just use the one I include in my releases?

I have never seen the screen that you are on which leads me to believe your issue is 1 of the following:
1. You downloaded a new certificate and tried to do this manually which is fine but may have incorrectly named a file and used the 32bit version instead of 64bit
2. I don't believe I clearly indicated this in the instructions since I was paraphrasing someone else's directions but if you have multiple OS's installed it will prevent the enrollment certificate menu from loading to allow you to install it. Try the following if you have multiple OS's installed:
a. Create a USB boot disk with one of my clean releases and then backup your current EFI and save it somewhere safe. 
b. Either delete your current EFI or rename it so your computer won't try to boot from it and so the modified grub wont see it as an option. 
c. Boot to the USB (with secure boot on in UEFI and you should be able to follow the remaining steps to get it running. 


Let me know if you are able to get this running.

**Comment by theholyjosh1** [comment] 2023-07-04 18:27
So as I was looking at the guide on the page, after I started copying the files to my efi I didn’t realise you actually had included all the files. I thought it would be fine so I replaced all the files you had with files I downloaded manually. Also the only OS installed is macOS. Will I have to try and install macOS again?

**Comment by balopez83** [comment] 2023-07-05 08:12
@ShibeGG1 So you definitely won’t need to reinstall macOS. 

While you can work with what you have done I highly recommend just restoring all files/folders within the EFI folder as provided in my release. You can keep your OC folder with any changes you have made. 

Specifically you must have the key, grub folder, and the boot folder as constructed in my release. There are two files within the boot folder that are changed in my release to allow it to boot to OpenCore while having the security key enrolled and I suspect you overwrote them when you made your own version which is likely why your computer was booting to that odd menu.

**Comment by theholyjosh1** [comment] 2023-07-05 13:50
Unless I am missing something, I can’t seem to get access to back to macOS. Turning secure boot on and off, uninstalling and installing secure boot keys from bios all do nothing. If I try to select an option from the ‘odd menu’ let’s call it, it will come up with and error showing a directory of some sort then saying not found or no server is specified or no such device. Here is a picture of me selecting a random option: then another picture of me selecting ‘Super Grub2 Disk’ and also another one of ‘Grub Live ISO Multiboot’ ![image](https://github.com/balopez83/Surface_Pro_3_Hackintosh/assets/118050388/82f90ba7-29d8-4c4c-bfec-b8297847b116)![image](https://github.com/balopez83/Surface_Pro_3_Hackintosh/assets/118050388/f6e2e4fd-2fca-4647-9baa-468626235ed6)![image](https://github.com/balopez83/Surface_Pro_3_Hackintosh/assets/118050388/266c703a-4405-4956-82ad-ed61742ecc3f)

**Comment by balopez83** [comment] 2023-07-06 18:23
@ShibeGG1 So if you are still seeing those screens you still haven't replaced all the files in your EFI with those in my release (make sure you use the release version you are currently using and not a newer/older version or you will have other issues). 
You really need to replace all files and folders in your EFI folder. The only folder that can remain the same is the OC folder within the EFI. 

Since you have now deleted keys in your UEFI you now have another new issue you may have introduced. Make sure that secure boot is enabled and that it is set for Microsoft and 3rd party keys. Anything other than that will cause a boot failure

Edit 1: If the issue is that you need to get back to macOS to fix your files you won't be able to in your current state. You will likely need to either: Use your macOS USB installer with my release EFI installed on it that you used to install macOS to boot to macOS installed on your Surface Pro OR you will need a Linux live USB to get access to your EFI and restore the correct files. 

Edit 2: If you use the macOS USB installer with my EFI release on it to get back into macOS you might actually be prompted to install your keys. You can do this here and the keys will remain installed after you finish restoring the files to your Surface Pro SSD EFI.

**Comment by balopez83** [comment] 2023-07-11 06:09
@ShibeGG1 I am assuming this has been resolved and so closing this issue. If you have any more issues with this just reopen this issue and I will do my best to assist.

**Closed as completed by balopez83** 2023-07-11 06:09 UTC
