### ISSUE TITLE
Graphical issues

### ISSUE THREAD

**Issue by theholyjosh1** [balopez83/Surface_Pro_3_Hackintosh#9] opened 2023-05-13 21:09 UTC
Ever since I have used this I have experienced graphical glitches on graphic intensive apps like Final Cut Pro, any game, Apple Maps, Spotify and much more. Any help would be appreciated.https://github.com/balopez83/Surface_Pro_3_Hackintosh/assets/118050388/193d7378-88a7-4b14-ac81-a6909f219c69

**Comment by balopez83** [comment] 2023-05-14 05:43
@ShibeGG1 Which version EFI did this begin to occur or has it always been an issue? What version macOS are you using? Also what specs and version of Surface Pro 3 do you have? Its possible you have an alternate version that isn't compatible with the graphics settings. included in the current EFI

**Comment by theholyjosh1** [comment] 2023-05-14 12:19
> @ShibeGG1 Which version EFI did this begin to occur or has it always been an issue? What version macOS are you using? Also what specs and version of Surface Pro 3 do you have? Its possible you have an alternate version that isn't compatible with the graphics settings. included in the current EFI

I am not sure which version efi I am using but I have the i7 512gb 8gb ram and hd 5000 model with macOS Big Sur 11.7.4

**Comment by theholyjosh1** [comment] 2023-05-14 12:39
As I see now there is a fix for my problem in 5.0.0 and I will install that aswell as Ventura now.

**Comment by balopez83** [comment] 2023-05-14 16:20
@ShibeGG1 Please don't upgrade to Ventura yet. Since the graphics is not officially supported by macOS on Ventura it requires patching which will introduce more variables interfering with troubleshooting.

Your issue is due to an incorrect graphics setting as this EFI is only for the i3 and i5 models of the Surface Pro 3. I can add support for your i7, but need you to test different config.plists files for me as I won't be able to since I don't have that graphics model to test on. You will need to test them on macOS 12.x.x versions or lower so Big Sur, Monterey, Catalina, are all good. We can't test and fix this on Ventura as it will break the OpenCore Patcher fix every time we test. 

As for Ventura please make sure you have OpenCore Patcher downloaded and ready before you go to Ventura as it is painfully slow until you patch it.

If you have already installed my 5.0.0 version EFI please let me know if it resolved your graphics glitches as I did make some changes with your other issue in mind. Please only report back on how it's working if your not on Ventura as it really won't be a good test. If graphics issues are a concern I might recommend holding off on Ventura for the time being as it may never be graphics glitch free due to the way it patches.

**Comment by balopez83** [comment] 2023-05-15 03:50
@ShibeGG1 Please see release 5.1.0 to see if it resolves your graphics issues. Others have said that their i7 no longer has screen artifacts/glitches. 

If I don't hear back in a few days I will go ahead and close this issue.

**Comment by theholyjosh1** [comment] 2023-05-15 18:37
@balopez83 As of now I am on Monterey now on the efi 5.1 release and the graphical artifacts are fixed. One issue I am having, I use my iPhone 11 with a mobile hotspot plugged into the surface and it used to work on big sur, but now it says the usb device is using too much power and network preferences says iPhone usb is disconnected.

**Comment by balopez83** [comment] 2023-05-16 00:57
@ShibeGG1 Glad to hear graphics is working properly now. I will look into the USB power issues and see what's wrong. Its possible I need to fix something in some of the ACPI code and issue a new release.

**Comment by balopez83** [comment] 2023-05-16 04:40
@ShibeGG1 can you tell me what EFI version you were on where the USB power was working properly? I have been trying to find the issue looking back at old EFI's and can't seem to find what is causing the issue yet. If you know which one was working I might be able to narrow down where the problem is occurring.

**Comment by balopez83** [comment] 2023-05-16 06:34
@ShibeGG1 I suspect you might have used the EFI that used to be in the main repository and not the Releases? I am looking into the USB issue and I suspect that the issue is that the SMBIOS we are using is causing macOS to handle USB ports differently. The typical method of adding additional power isn't seeming to work because its designed for the SMBIOS we are using BUT the computer isn't matching the SMBIOS and so its still not going to handle things properly. 

The last time the SMBIOS was set properly to potentially drive the USB properly was version 1.0.0 however that release isn't capable of running Monterey. I am going to try and install an older OS to test this theory but suspect that it is going to be difficult to get this to work on Monterey or newer as I believe Apple removed some of the support for the SP3 hardware. 

I will keep working on it but if you have the EFI you used that you said did work on Big Sur and gave you USB support for high current devices and can send it to me it will help me get to the bottom of this faster. At a min it will get me pointed in the right direction.

Assuming the SMBIOS thing is the issue and with newer macOS versions requiring this SMBIOS, I may need to look deeper into some ACPI settings that I think might resolve the issues but that will take some time.

**Comment by theholyjosh1** [comment] 2023-05-16 09:08
@balopez83  I am unable to send a used one if you know what I mean, but I am %90 sure it was release 4.0.0 used on big sur because on future releases the graphics issues were patched and I don't remember why, but I never updated my efi after the audio issues were fixed so I'm pretty sure it was 4.0.0

**Comment by theholyjosh1** [comment] 2023-05-16 15:47
Something I have just discovered is when plugging in my phone to a usb hub then into the surface, it works just fine!

**Comment by Nyryzu** [comment] 2023-05-16 22:28
Heey! I have the same USB problem on my SP3 I7 model as well, I got an android which I was using in tether mode all this time and it works perfectly but after reading your issues I decided to plug my Iphone for fun and see if the same thing happens and indeed it does! It shuts off the usb port and asks me to remove the device to restore functionality again and my Iphone is stuck back and forth between charging and not charging modes

**Comment by balopez83** [comment] 2023-05-16 22:47
@Nyryzu @ShibeGG1 , I have found the issue that is causing it and working on a new release that will fix the problem. Since release 5.0.0 I tried to clean up the ACPI code but introduced a problem that impacted USB that was not apparent at the time. 

It may be a couple days (hopefully sooner) before I can issue a release fixing it as I found some other things I am fixing and adding to the next release. Plus its crazy busy at work. 

In the interim it seems that @ShibeGG1 found that if you plug the phone into a USB hub and then plug that in to the USB port, it may work for tethering and charging (I suspect a slow charge). The fix I am issuing will provide full power to all USB devices.

**Comment by theholyjosh1** [comment] 2023-05-17 06:09
Thanks very much! Just saying, take your time there's no hurry! 🙃

**Comment by frank6311** [comment] 2023-05-18 17:32
No question actually.  Just wanted to thank you for your work on this.  The latest release is working pretty much flawlessly on my Surface Pro 3 i5.  Some web pages in Safari won't load properly but I think that may be a mac issue rather than your EFI.  Thanks again

**Comment by balopez83** [comment] 2023-05-18 17:46
@frank6311 Thank you. I am thrilled that there is still people wanting to do this on this old tablet and the fact that it can work as well as it does is exciting. Hope to be able to support this for some time and bring more features in the future. 

@ShibeGG1 & @Nyryzu , since you have the i7 models, can you confirm that graphics is still running well on EFI release 5.2.0? I changed the graphics around a bit more as I was using a desktop model identifier to drive things in earlier releases which limited the brightness the screen could reach. 

I am pretty sure that graphics, USB, and many of the other items should be working now and so will close this issue as resolved. If for some reason graphics acts up again on the i7 model, go ahead and reopen this issue.

**Closed as completed by balopez83** 2023-05-18 17:46 UTC

**Comment by frank6311** [comment] 2023-05-20 15:40
If I can...I have a quick question.  When I update to the latest release do
I need to do anything other than replace the EFI?
Thanks

**Comment by balopez83** [comment] 2023-05-20 17:49
@frank6311 That question is a little complicated but here is the short an sweet response: 

- If you have followed the directions to use iServices (e.g. iMessage, FaceTime, etc.) then you need to be sure to copy your information over to the new config or you will break all of those services. If you haven't done that yet then you can skip this.
- I have changed some pretty important items in the last few EFI releases and so I always recommend Cleaning/Resetting NVRAM in my release notes (only referenced r5.1.0 which has it though prob should have said it in this one). In this case I HIGHLY recommend it because if something sticks in NVRAM which happens all the time, you could have problems and not be able to fix them even though there shouldn't have been a problem to begin with (OpenCore does this intentionally to prevent premature wear out of the NVRAM). You can do this by simply pressing the space bar when the boot menu pops up when you first start the computer.

**Comment by frank6311** [comment] 2023-05-20 18:34
Great.  Thanks for the response!

**Comment by theholyjosh1** [comment] 2023-05-21 18:59
Might want to re open this issue,the graphic glitches are back in the new efi version.

**Comment by theholyjosh1** [comment] 2023-05-21 19:00
For now I am going to downgrade to 5.1 let me know if you need anything
